use `shiny`;
-- ----------------------------
-- 5、采集配置表数据
-- ----------------------------
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1, 'Movist', 'http://xclient.info/s/movist.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '一款CPU占用率低的高清多格式媒体播放器');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2, 'Things', 'http://xclient.info/s/things.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '一款优秀的GTD任务管理工具');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3, 'iStatistica', 'http://xclient.info/s/istatistica.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '一款高颜值的系统监控工具');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (4, 'TinyCal', 'http://xclient.info/s/tinycal.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '小历 - 小而美的日历');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (5, 'Money Pro', 'http://xclient.info/s/money-pro.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '可同步账单、预算和账户');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (6, 'OmniPlan', 'http://xclient.info/s/omni-plan.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '专业版 最NB的项目管理流程软件');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (7, 'Navicat Premium', 'http://xclient.info/s/navicat-premium.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '强大的数据库管理工具');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (8, 'OmniGraffle Pro', 'http://xclient.info/s/omnigraffle.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '强大的图形工具');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (9, 'XMind 8 Pro', 'http://xclient.info/s/xmind.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '最受欢迎思维导图软件');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (10, 'StarUML', 'http://xclient.info/s/staruml.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '强大的UML工具');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (11, 'ScreenFlow', 'http://xclient.info/s/screenflow.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '优秀的屏幕录像软件');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (12, 'EdrawMax', 'http://xclient.info/s/edraw-max.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '亿图图示专家 基于矢量的绘图工具');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (13, 'Charles', 'http://xclient.info/s/charles.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', 'Mac上的抓包工具');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (14, 'SnippetsLab', 'http://xclient.info/s/snippetslab.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '构建你的私人代码片段库');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (15, 'Adobe Photoshop CC', 'http://xclient.info/s/adobe-photoshop-cc.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (16, 'Adobe Photoshop Lightroom CC', 'http://xclient.info/s/adobe-lightroom-cc.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (17, 'VMware Fusion', 'http://xclient.info/s/vmware-fusion.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '强大的虚拟机应用');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (18, 'Tuxera NTFS', 'http://xclient.info/s/tuxera-ntfs.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '让你的Mac支持NTFS');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (19, 'Parallels Desktop', 'http://xclient.info/s/parallels-desktop.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '最佳Mac虚拟机解决方案');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (20, 'Microsoft Office', 'http://xclient.info/s/office-for-mac.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '多国语言大客户版');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (21, 'Beyond Compare', 'http://xclient.info/s/beyond-compare.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '文件对比利器');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (22, 'Sublime Text', 'http://xclient.info/s/sublime-text.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '一款优秀的代码编辑器');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (23, 'UltraEdit', 'http://xclient.info/s/ultraedit.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '老牌文本编辑器');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (24, 'Understand', 'http://xclient.info/s/understand.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '代码阅读分析软件');
INSERT INTO `spider_config`(`id`, `spider_name`, `spider_url`, `last_spider_time`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (25, 'Paste', 'http://xclient.info/s/paste-for-mac.html', NULL, '管理员', '2018-09-10 00:00:00', '管理员', '2018-09-10 00:00:00', '剪切板增强工具');
